// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
      
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.js

import './globals.css'
import { Kosugi_Maru } from 'next/font/google'

const kosugi = Kosugi_Maru({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-kosugi',
})

export const metadata = {
  title: '心理測驗',
  description: '你是哪種大學生？',
}

export default function RootLayout({ children }) {
  return (
    <html lang="zh-Hant" className={kosugi.variable}>
      <body>{children}</body>
    </html>
  )
}

